"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ref_column import RefColumn


class TestRefColumn(unittest.TestCase):
    """RefColumn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRefColumn(self):
        """Test RefColumn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RefColumn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
