"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import priceloop_api
from priceloop_api.model.api_external_function import ApiExternalFunction


class TestApiExternalFunction(unittest.TestCase):
    """ApiExternalFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiExternalFunction(self):
        """Test ApiExternalFunction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiExternalFunction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
