"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.num_lit import NumLit


class TestNumLit(unittest.TestCase):
    """NumLit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNumLit(self):
        """Test NumLit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NumLit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
