"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import priceloop_api
from priceloop_api.apis.tags.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_table(self):
        """Test case for get_table

        """
        pass

    def test_get_table_data(self):
        """Test case for get_table_data

        """
        pass

    def test_get_workspace(self):
        """Test case for get_workspace

        """
        pass

    def test_list_workspaces(self):
        """Test case for list_workspaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
