"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.expression import Expression
from openapi_client.model.op_sym import OpSym
globals()['Expression'] = Expression
globals()['OpSym'] = OpSym
from openapi_client.model.infix_call import InfixCall


class TestInfixCall(unittest.TestCase):
    """InfixCall unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfixCall(self):
        """Test InfixCall"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InfixCall()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
