"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import priceloop_api
from priceloop_api.model.api_table import ApiTable
globals()['ApiTable'] = ApiTable
from priceloop_api.model.api_workspace import ApiWorkspace


class TestApiWorkspace(unittest.TestCase):
    """ApiWorkspace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiWorkspace(self):
        """Test ApiWorkspace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiWorkspace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
