"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.connector import Connector
from openapi_client.model.filter_op import FilterOp
globals()['Connector'] = Connector
globals()['FilterOp'] = FilterOp
from openapi_client.model.condition_ref import ConditionRef


class TestConditionRef(unittest.TestCase):
    """ConditionRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionRef(self):
        """Test ConditionRef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConditionRef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
