"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.column import Column
from openapi_client.model.table_view import TableView
globals()['Column'] = Column
globals()['TableView'] = TableView
from openapi_client.model.table import Table


class TestTable(unittest.TestCase):
    """Table unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTable(self):
        """Test Table"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Table()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
