"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import priceloop_api
from priceloop_api.model.table_data import TableData


class TestTableData(unittest.TestCase):
    """TableData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTableData(self):
        """Test TableData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TableData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
