"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_expression import ApiExpression
from openapi_client.model.ct_formula import CtFormula
globals()['ApiExpression'] = ApiExpression
globals()['CtFormula'] = CtFormula
from openapi_client.model.api_column_type import ApiColumnType


class TestApiColumnType(unittest.TestCase):
    """ApiColumnType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiColumnType(self):
        """Test ApiColumnType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiColumnType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
