"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.expression import Expression
globals()['Expression'] = Expression
from openapi_client.model.if_else import IfElse


class TestIfElse(unittest.TestCase):
    """IfElse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIfElse(self):
        """Test IfElse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IfElse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
