"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.t_narrow import TNarrow
globals()['TNarrow'] = TNarrow
from openapi_client.model.expr_type import ExprType


class TestExprType(unittest.TestCase):
    """ExprType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExprType(self):
        """Test ExprType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExprType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
