"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.table import Table
globals()['Table'] = Table
from openapi_client.model.workspace import Workspace


class TestWorkspace(unittest.TestCase):
    """Workspace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspace(self):
        """Test Workspace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Workspace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
