"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.expression import Expression
from openapi_client.model.func_sym import FuncSym
globals()['Expression'] = Expression
globals()['FuncSym'] = FuncSym
from openapi_client.model.builtin_call import BuiltinCall


class TestBuiltinCall(unittest.TestCase):
    """BuiltinCall unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuiltinCall(self):
        """Test BuiltinCall"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BuiltinCall()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
