"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.expr_type import ExprType
globals()['ExprType'] = ExprType
from openapi_client.model.null_lit import NullLit


class TestNullLit(unittest.TestCase):
    """NullLit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNullLit(self):
        """Test NullLit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NullLit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
