"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.expression import Expression
from openapi_client.model.ident import Ident
globals()['Expression'] = Expression
globals()['Ident'] = Ident
from openapi_client.model.call import Call


class TestCall(unittest.TestCase):
    """Call unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCall(self):
        """Test Call"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Call()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
