"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sorting_order import SortingOrder
globals()['SortingOrder'] = SortingOrder
from openapi_client.model.sort_condition_ref import SortConditionRef


class TestSortConditionRef(unittest.TestCase):
    """SortConditionRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortConditionRef(self):
        """Test SortConditionRef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SortConditionRef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
