"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.aggregate_sym import AggregateSym
from openapi_client.model.builtin_call import BuiltinCall
from openapi_client.model.call import Call
from openapi_client.model.column_sym import ColumnSym
from openapi_client.model.date_lit import DateLit
from openapi_client.model.expr_type import ExprType
from openapi_client.model.false_lit import FalseLit
from openapi_client.model.func_sym import FuncSym
from openapi_client.model.ident import Ident
from openapi_client.model.if_else import IfElse
from openapi_client.model.infix_call import InfixCall
from openapi_client.model.join_expr import JoinExpr
from openapi_client.model.null_lit import NullLit
from openapi_client.model.num_lit import NumLit
from openapi_client.model.op_sym import OpSym
from openapi_client.model.ref_column import RefColumn
from openapi_client.model.str_lit import StrLit
from openapi_client.model.true_lit import TrueLit
globals()['AggregateSym'] = AggregateSym
globals()['BuiltinCall'] = BuiltinCall
globals()['Call'] = Call
globals()['ColumnSym'] = ColumnSym
globals()['DateLit'] = DateLit
globals()['ExprType'] = ExprType
globals()['FalseLit'] = FalseLit
globals()['FuncSym'] = FuncSym
globals()['Ident'] = Ident
globals()['IfElse'] = IfElse
globals()['InfixCall'] = InfixCall
globals()['JoinExpr'] = JoinExpr
globals()['NullLit'] = NullLit
globals()['NumLit'] = NumLit
globals()['OpSym'] = OpSym
globals()['RefColumn'] = RefColumn
globals()['StrLit'] = StrLit
globals()['TrueLit'] = TrueLit
from openapi_client.model.expression import Expression


class TestExpression(unittest.TestCase):
    """Expression unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExpression(self):
        """Test Expression"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Expression()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
