"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.condition_ref import ConditionRef
from openapi_client.model.sort_condition_ref import SortConditionRef
globals()['ConditionRef'] = ConditionRef
globals()['SortConditionRef'] = SortConditionRef
from openapi_client.model.table_view import TableView


class TestTableView(unittest.TestCase):
    """TableView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTableView(self):
        """Test TableView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TableView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
