"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "priceloop-api"
VERSION = "0.1.3.2-beta"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.25.3", "python-dateutil", "requests", "boto3", "pandas"]

setup(
    name=NAME,
    version=VERSION,
    description="Priceloop API",
    author="Priceloop",
    author_email="hello@priceloop.ai",
    url="https://github.com/priceloop/priceloop-api-python",
    keywords=["Priceloop API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    Connect to your Priceloop Data through our API
    """,
)
