"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

import os
import re


def text_of(relpath):
    """
    Return string containing the contents of the file at *relpath* relative to
    this file.
    """
    thisdir = os.path.dirname(__file__)
    file_path = os.path.join(thisdir, os.path.normpath(relpath))
    with open(file_path) as f:
        text = f.read()
    return text


NAME = "priceloop-api"
VERSION = re.search(
    '__version__ = "([^\']+)"', text_of("priceloop_api/__init__.py")
).group(1)

REQUIRES = [
    "urllib3 >= 1.25.3",
    "boto3~=1.24.78",
    "requests==2.25",
    "python-dateutil~=2.8.2",
    "frozendict==2.3.4",
    "pandas==1.5.2",
    "typing_extensions==4.4.0",
]

setup(
    name=NAME,
    version=VERSION,
    description="Priceloop API",
    author="Priceloop",
    author_email="hello@priceloop.ai",
    url="https://github.com/priceloop/priceloop-api-python",
    keywords=["Priceloop API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    Connect to your Priceloop Data through our API
    """,
)
