# coding: utf-8

"""
    Priceloop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from priceloop_api.paths.api_v1_0_workspaces_workspace_tables_table.delete import DeleteTable
from priceloop_api.paths.api_v1_0_workspaces_workspace_tables_table.get import GetTable
from priceloop_api.paths.api_v1_0_workspaces_workspace_tables_table_data.get import GetTableData
from priceloop_api.paths.api_v1_0_workspaces_workspace_tables_table_upload_csv_url.get import GetTableUploadCsvUrl
from priceloop_api.paths.api_v1_0_workspaces_workspace.get import GetWorkspace
from priceloop_api.paths.api_v1_0_workspaces.get import ListWorkspaces


class DefaultApi(
    DeleteTable,
    GetTable,
    GetTableData,
    GetTableUploadCsvUrl,
    GetWorkspace,
    ListWorkspaces,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
