name: Build

on:
  push:
    branches: ["*"]
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: "Build"
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: "pip"

      - name: build package
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

  publish:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-22.04
    name: "Publish python package on PyPI"
    strategy:
      matrix:
        python-version: ["3.8"]
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
