name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: "Build"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Pip Install
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Test
        run: |
          pytest --cov=priceloop_api
